# Generated by Django 4.1.5 on 2023-01-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\Hazem Darwich\\Desktop\\WebProjects\\New SHOP\\Media'),
        ),
    ]
